config/routes.rb
Rails.application.routes.draw do
  resources :account_histories
  resources :accounts
  resources :appointments
  resources :patients
  resources :physicians

  root'appointments#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account_history.rb
class AccountHistory < ApplicationRecord 
	belongs_to :account
end

app/controllers/account_histories_controller.rb
class AccountHistoriesController < ApplicationController
  before_action :set_account_history, only: %i[ show edit update destroy ]

  # GET /account_histories or /account_histories.json
  def index
    @account_histories = AccountHistory.all
  end

  # GET /account_histories/1 or /account_histories/1.json
  def show
  end

  # GET /account_histories/new
  def new
    @account_history = AccountHistory.new
  end

  # GET /account_histories/1/edit
  def edit
  end

  # POST /account_histories or /account_histories.json
  def create
    @account_history = AccountHistory.new(account_history_params)

    respond_to do |format|
      if @account_history.save
        format.html { redirect_to @account_history, notice: "Account history was successfully created." }
        format.json { render :show, status: :created, location: @account_history }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @account_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /account_histories/1 or /account_histories/1.json
  def update
    respond_to do |format|
      if @account_history.update(account_history_params)
        format.html { redirect_to @account_history, notice: "Account history was successfully updated." }
        format.json { render :show, status: :ok, location: @account_history }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @account_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /account_histories/1 or /account_histories/1.json
  def destroy
    @account_history.destroy
    respond_to do |format|
      format.html { redirect_to account_histories_url, notice: "Account history was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account_history
      @account_history = AccountHistory.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def account_history_params
      params.require(:account_history).permit(:patient_status, :account_id)
    end
end

app/helpers/account_histories_helper.rb
module AccountHistoriesHelper
end

app/views/account_histories/_form.html.erb
<%= form_with(model: account_history, local: true) do |form| %>
  <% if account_history.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(account_history.errors.count, "error") %> prohibited this account_history from being saved:</h2>

      <ul>
      <% account_history.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :patient_status %>
    <%= form.text_field :patient_status %>
  </div>

  <div class="field">
    <%= form.label :account_number %>
    <%= collection_select(:account_history, :account_id,Account.all, :id, :account_number, prompt: true) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/account_histories/edit.html.erb
<h1>Editing Account History</h1>

<%= render 'form', account_history: @account_history %>

<%= link_to 'Show', @account_history %> |
<%= link_to 'Back', account_histories_path %>

app/views/account_histories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Account Histories</h1>

<%= link_to 'Accounts', accounts_path %>

<table>
  <thead>
    <tr>
      <th>Patient status</th>
      <th>Account Number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @account_histories.each do |account_history| %>
      <tr>


        <td><%= account_history.patient_status %></td>

        <td><%= account_history.account.account_number %></td>

        <td><%= link_to 'Show', account_history %></td>
        <td><%= link_to 'Edit', edit_account_history_path(account_history) %></td>
        <td><%= link_to 'Destroy', account_history, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Account History', new_account_history_path %>

app/views/account_histories/new.html.erb
<h1>New Account History</h1>

<%= render 'form', account_history: @account_history %>

<%= link_to 'Back', account_histories_path %>

app/views/account_histories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Patient status:</strong>
  <%= @account_history.patient_status %>
</p>

<p>
  <strong>Account Number</strong>
  <%= @account_history.account.account_number %>
</p>



<%= link_to 'Edit', edit_account_history_path(@account_history) %> |
<%= link_to 'Back', account_histories_path %>